### ISSUE TITLE
Allow Cleaner use with forms=False

### ISSUE THREAD

**Issue by jsonn** [matthiask/html-sanitizer#5]
The LXML cleaner will strip all form elements by defaults. For my use case, this is quite annoying as radio/check boxes and select fields are quite useful as real-world form elements. In fact, I wonder if explicitly stripping of <form> and handling the rest as normal tags wouldn't serve the purpose better. Alternatively, making the forms value optional and defaulting to True would work as well for me.

**Comment by matthiask** [comment]
Hmm, where do the `<form>` elements come from? Do you have users creating forms in rich text editors? What is the specific use case?

We only sanitize HTML entered by users (and staff, of course, but those are users of the CMS); forms don't qualify because most often they also require backend support and so are different anyway. If users should be able to build forms themselves, I use https://github.com/feincms/form_designer

(I'm not necessarily opposed to adding `forms`, but I don't see the use case yet.)

**Comment by jsonn** [comment]
I don't care about `<form>` at all, but the same option also filters all `<input>`, `<button>` and `<select>` tags. I do care about certain `<input>` types and `<select>`. CKEditor has a plugin for editing them and I use that as part of an editor for common text fragments. The normal users just have the option of inserting such a fragment and ticking the boxes / selecting options. E.g. consider a paper form like:

```
( ) Choice 1
( ) Choice 2
```

Representing this as actual `<input type="radio">` fields has the advantage that it provides sane space etc.

**Comment by matthiask** [comment]
I see!

Form tags' contents aren't preserved: https://github.com/lxml/lxml/blob/4507da6f8f8e7fd6d68c6b7ec2e37b1b0a7f214f/src/lxml/html/clean.py#L360

Right now the sanitizer does not have a list of tags to kill but only to remove. Otherwise we could just pass `forms=True` (and maybe also embeds, etc.) and handle everything via our own whitelists...

**Comment by matthiask** [comment]
Fixed by #6.
